done_setup: false

mysql:
    host: "localhost"
    port: 3306
    dbname: "mtest2"
    user: "root"
    password: ""
    table: "stats"

table:
    #row you save player name
    playername: "name"
    #row you save player kill
    killrow: "kills"
    #row you save player win
    winrow: "wins"
    #row you save player score
    scorerow: "scores"
    #row you save player roundplayed
    roundrow: "rounds"
    
    
kill:
    world: "world"
    x: 0.5
    y: 104.5
    z: -3.5
    title: "&6Most kills"
    item: "iron_sword"
        
win:
    world: "world"
    x: 0.5
    y: 104.5
    z: 0.5
    title: "&6Most wins"
    item: "nether_star"
        
score:
    world: "world"
    x: 0.5
    y: 104.5
    z: 4.5
    title: "&6Highest scores "
    item: "gold_ingot"
        
played:
    world: "world"
    x: 0.5
    y: 104.5
    z: 8.5
    title: "&6Most played"
    item: "diamond_block"